######################################## Application ########################################################

appName: usermanagment-helm
namespace: helm-test

######################################### configmap #########################################################

configmap:
  name: fastapi-helm-config
                                  ######### mysql ###########  
  analyseNotificationServiceUrl: http://10.96.227.86:31853                                                              
  mysql:
    user: root
    ip: mysql-istio.app-istio
    port: 3306
    password: 1234
    dbname: pfedb

########################################## Image ############################################################

image:
  repository: firaschikhaoui/usermanagment
  tag: v1