######################################## Application ########################################################

appName: backhelm
namespace: argoapp

######################################### configmap #########################################################

configmap:
  name: fastapi-configtest
                                  ######### mysql ###########                              
  mysql:
    user: root
    ip: mysql.default
    port: 3306
    password: 1234
    dbname: pfedb

########################################## Image ############################################################

image:
  repository: firaschikhaoui/test-backv5
  tag: latest

  
