######################################## Application ########################################################

appName: usermanagment-helm
namespace: app-istio

######################################### configmap #########################################################

configmap:
  name: fastapi-helm-config
                                  ######### mysql ###########  
  analyseNotificationServiceUrl: notifications-helm.app-istio                                                              
  mysql:
    user: root
    ip: mysql-istio.app-istio
    port: 3306
    password: 1234
    dbname: pfedb

########################################## Image ############################################################

image:
  repository: firaschikhaoui/usermanagment
  tag: v1
